services:
  faucet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8088:8088"
    environment:
      - NODE_ENV=production
      - PORT=8088
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      # Persist rate limiting database
      - faucet-data:/app/.faucet
      # Allow hot reload of config files in development
      - ./tokens.json:/app/tokens.json:ro
      - ./deployments:/app/deployments:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  faucet-data:
