[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
]
optimizer = true
optimizer_runs = 200
evm_version = "istanbul"
solc_version = "0.8.28"